#!/usr/bin/env python3
"""Editable Matplotlib reconstruction of the quantum linear regression schematic.

Requirements: numpy, matplotlib and a LaTeX installation with the
amsfonts, amssymb, mathpazo and bm packages (no source images or PDF files needed).
Text is typeset with LaTeX in the same style as the other paper figures.
Run: python qlr_figure_matplotlib.py --output-dir . --dpi 200

Exports PDF, SVG and PNG. All artists are generated by Matplotlib.
Panel a shows schematic singular values in each matrix's own SVD basis;
its two hues share a logarithmic magnitude scale. Panel c is illustrative,
not a fit or simulation. Edit A, B, FLOOR, AMP and CAP to change the curves.
Canvas coordinates are 1800 x 1100, with the origin at the top left.
"""
import argparse
from pathlib import Path
import numpy as np
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
from matplotlib.patches import Rectangle, FancyBboxPatch, Circle, Polygon


def build_figure():
    # Same LaTeX style as the other figures of the paper (Palatino via mathpazo).
    plt.rcParams["text.latex.preamble"] = r"\usepackage{amsfonts, amssymb, mathpazo,bm}"
    plt.rcParams.update({"text.usetex": True, "font.family": "serif",
                         "svg.fonttype": "none", "pdf.fonttype": 42})
    teal='#10858b'; orange='#ca6533'; ink='#282e34'; grey='#778795'
    fig=plt.figure(figsize=(18,11),facecolor='white')
    ax=fig.add_axes([0,0,1,1]);ax.set_xlim(0,1800);ax.set_ylim(1100,0);ax.axis('off')
    def text(x,y,s,size=14,color=ink,weight='normal',**kw):
     # With usetex the fontweight is ignored, so bold is applied in LaTeX,
     # line by line because Matplotlib typesets each line separately.
     if weight=='bold':
      s='\n'.join(r'\textbf{'+line+'}' for line in s.split('\n'))
     ax.text(x,y,s,fontsize=size,color=color,va='center',**kw)
    def arrow(x1,y1,x2,y2,color=grey):
     ax.annotate('',xy=(x2,y2),xytext=(x1,y1),arrowprops=dict(arrowstyle='->',lw=1.4,color=color))
    def shade(value,base):
     import matplotlib.colors as c
     if value==0:return '#ffffff'
     t=(np.log10(value)+2)/3.6
     t=.12+.88*np.clip(t,0,1)
     return tuple((1-t)*np.ones(3)+t*np.array(c.to_rgb(base)))
    def matrix(x,y,vals):
     size=17.5
     for i in range(8):
      for j in range(8):
       v=vals[i] if i==j else 0
       ax.add_patch(Rectangle((x+j*size,y+i*size),size,size,facecolor=shade(v,teal if i<4 else orange),edgecolor='#e4e9ec',linewidth=.55))
     ax.add_patch(Rectangle((x,y),8*size,8*size,fill=False,edgecolor='#aebac2',linewidth=.8))
     ax.plot([x+4*size,x+4*size],[y,y+8*size],color='#aebac2',lw=.7,ls=(0,(3,3)))
     ax.plot([x,x+8*size],[y+4*size,y+4*size],color='#aebac2',lw=.7,ls=(0,(3,3)))
    def colorbar(x,y):
     # Both hues use the same logarithmic magnitude scale.
     for k in range(140):
      value=10**(1.6-3.6*k/139)
      for j,base in enumerate([teal,orange]):
       ax.add_patch(Rectangle((x+8*j,y+k),8,1.02,facecolor=shade(value,base),edgecolor='none'))
     ax.add_patch(Rectangle((x,y),16,140,fill=False,edgecolor='#aebac2',linewidth=.6))
     text(x+22,y+3,'large',9,grey)
     text(x+22,y+137,'small',9,grey)
     for j in range(2):
      ax.add_patch(Rectangle((x+8*j,y+146),8,8,facecolor='white',edgecolor='#aebac2',linewidth=.6))
     text(x+22,y+150,'0',9,grey)
    # Panel a layout. Each column (title, matrix, annotations) is centred on its
    # matrix; titles, matrices, scaling labels and captions each share one row.
    col_x=[221,665,1109]            # column centres (matrix centres)
    mat_top,mat_size=140,140        # matrices are 8 x 17.5 = 140 wide
    mid_y=mat_top+mat_size/2
    text(50,44,r'a\quad Shot noise lifts the rank',24,weight='bold')
    text(col_x[1],43,'Singular values (schematic)',11,grey,ha='center')
    for cx,title in zip(col_x,['Ideal probabilities','Finite-shot features','Pseudoinverse']):
        text(cx,107,title,17,weight='bold',ha='center')
    for cx,vals in zip(col_x,[[1,.8,.6,.45,0,0,0,0],
                              [1,.8,.6,.45,.04,.03,.025,.02],
                              [1,1/.8,1/.6,1/.45,25,1/.03,40,50]]):
        matrix(cx-mat_size/2,mat_top,vals)
        colorbar(cx+mat_size/2+14,mat_top)
    # Each arrow sits midway between a colour bar (with its labels) and the next matrix.
    bar_w=mat_size/2+61             # matrix half-width + gap + bar + labels
    def step(x_left,x_right,label):
        xm=(x_left+x_right)/2
        arrow(xm-70,mid_y,xm+70,mid_y)
        text(xm,mid_y-30,label,14,grey,ha='center')
    step(col_x[0]+bar_w,col_x[1]-mat_size/2,'shots')
    step(col_x[1]+bar_w,col_x[2]-mat_size/2,'invert')
    text(col_x[1],300,r'$\sim N^{-1/2}$',17,orange,ha='center')
    text(col_x[2],300,r'$\sim\sqrt{N}$',17,orange,ha='center')
    text(col_x[0],332,r'$\mathrm{rank}(P)\leq d^2$',16,grey,ha='center')
    text(col_x[1],332,'New noise-only directions',15,orange,ha='center')
    text(col_x[2],332,'Small modes, large inverse',15,orange,ha='center')
    # Preserve the two physical outcomes from the original panel.
    ax.plot([1288,1327,1327],[210,210,159],color='#d8e0e5',lw=1)
    ax.plot([1327,1327],[210,264],color='#d8e0e5',lw=1)
    arrow(1327,159,1365,159,teal);arrow(1327,264,1365,264,orange)
    text(1381,157,'Exact targets + exact test',15,teal,'bold')
    text(1381,190,'Divergence cancels',15,teal)
    text(1381,263,'Noisy targets + finite test',15,orange,'bold')
    text(1381,296,'Quantum overfitting',15,orange)
    # Panel b: individual sources of prediction error.
    purple = '#8a70aa'
    dark_teal = '#1a6072'
    text(50,390,r'b\quad Origins of the MSE',24,weight='bold')
    text(735,390,r'c\quad Resources shape the MSE',24,weight='bold')
    def box(x,y,w,h,color,style='-'):
     ax.add_patch(FancyBboxPatch((x,y),w,h,boxstyle='round,pad=0,rounding_size=13',
                               facecolor='white',edgecolor=color,lw=1.1,linestyle=style))
    def group_label(y,lines,color):
     text(173,y,lines,14,color,'bold',ha='right',linespacing=1.3)
    def divider(y):
     ax.plot([205,658],[y,y],color='#d6dfe4',lw=1)
    box(188,451,485,170,teal)
    group_label(520,'Training-shot\neffects',teal)
    divider(535)
    text(260,482,'Training bias',17,ink,'bold')
    text(260,513,'Training shot noise',14,teal)
    text(650,507,r'$N^{-2}$',20,teal,ha='right')
    text(260,561,'Training fluctuations',17,ink,'bold')
    text(260,595,'Training shot noise',14,teal)
    text(650,588,r'$1/(N\,n_{\mathrm{tr}})$',19,teal,ha='right')
    x=np.linspace(206,245,100)
    ax.plot(x,512-36*np.exp(-((x-227)/8)**2),color=teal,lw=1.6)
    arrow(213,465,237,465,teal)
    ax.scatter([215,234,220,241,212,232,224],[560,555,574,579,592,601,583],s=10,color=teal)
    box(188,641,485,169,purple)
    group_label(720,'Target noise\nClassical',purple)
    divider(726)
    text(260,672,'Training target noise',17,ink,'bold')
    text(260,705,'Noisy training labels',14,purple)
    text(650,702,r'$\gamma^2/n_{\mathrm{tr}}$',19,purple,ha='right')
    text(260,752,'Test target noise',17,ink,'bold')
    text(260,786,'Noisy test labels',14,purple)
    text(650,784,r'$\gamma^2$',20,purple,ha='right')
    ax.add_patch(Polygon([(210,665),(239,665),(250,685),(239,709),(210,709)],fill=False,edgecolor=purple,lw=1.3))
    text(224,686,r'$\pm$',18,purple,ha='center')
    ax.add_patch(Circle((239,677),2.6,fill=False,edgecolor=purple,lw=1))
    for radius in [12,22]:ax.add_patch(Circle((227,771),radius,fill=False,edgecolor=grey,lw=1))
    ax.scatter([216,226,238],[769,762,783],s=13,color=grey)
    box(188,831,485,84,grey,'--')
    group_label(872,'Test-shot\neffect',grey)
    text(260,854,'Test sampling',17,ink,'bold')
    text(260,888,'Finite test shots',14,grey)
    text(650,885,r'$1/M$',20,grey,ha='right')
    for j,h in enumerate([16,33,25,42]):ax.add_patch(Rectangle((208+j*11,892-h),6,h,facecolor=grey))
    box(188,936,485,112,orange,'--')
    group_label(989,'Quantum\noverfitting',orange)
    text(260,961,'Quantum overfitting',17,ink,'bold')
    text(260,995,r'Training-shot noise $\times$ target noise',13,orange)
    text(260,1022,r'$\times$ test-shot noise',13,orange)
    text(650,1022,r'$\gamma^2\,N/M$',20,orange,ha='right')
    ax.plot([207,222,234],[1000,980,986],color=orange,lw=1.7)
    arrow(234,986,251,963,orange)
    # Panel c: schematic log-log resource curves, not experimental data.
    # The capped training contribution interpolates between an undersampled
    # plateau and A/N^2 + B/N. Test noise and label amplification are additive.
    N=np.logspace(-1,6,500)
    A,B,FLOOR,AMP,CAP=8e-3,2e-5,8e-7,8e-10,1e-2
    raw=A/N**2+B/N
    train=CAP*raw/(CAP+raw)
    finite=train+FLOOR
    noisy=finite+AMP*N
    X0,X1,Y0,Y1=777,1585,1034,566
    log_min,log_max=-12.0,-1.7
    xx=X0+(np.log10(N)+1)/7*(X1-X0)
    def yy(values):
     return Y0-(np.log10(values)-log_min)/(log_max-log_min)*(Y0-Y1)
    # Subtle tinted regions use vector polygons for crisp PDF/SVG export.
    ax.add_patch(Rectangle((X0,Y1),X1-X0,Y0-Y1,facecolor='#eff7f7',edgecolor='none'))
    ax.fill_between(xx,Y1,np.minimum(yy(noisy),Y0),color='#fcf3ee',lw=0)
    ax.fill_between(xx,yy(noisy),yy(finite),color='#f2f4f6',lw=0)
    arrow(X0,Y0,X1+19,Y0,ink)
    arrow(X0,Y0,X0,Y1-15,ink)
    text(733,798,'MSE',19,ink,rotation=90,ha='center')
    text(1190,1076,r'Training shots per state, $N$',20,ink,ha='center')
    # Reproducible faint traces convey fluctuations without representing data.
    rng=np.random.default_rng(7)
    for curve,color in [(train,teal),(finite,grey),(noisy,orange)]:
     for _ in range(2):
      perturb=np.exp(rng.normal(0,.22,len(N[::5])))
      ax.plot(xx[::5],yy(curve[::5]*perturb),color=color,alpha=.22,lw=.9)
     ax.plot(xx,yy(curve),color=color if color!=teal else dark_teal,lw=2.7,solid_capstyle='round')
    # Asymptotic guide lines.
    for curve,mask,color in [(A/N**2,(N>1)&(N<100),teal),
                             (B/N,N>1e3,teal),
                             (AMP*N,N>1e4,orange)]:
     ax.plot(xx[mask],yy(curve[mask]),color=color,lw=1.2,ls=(0,(6,4)),alpha=.7)
    text(795,527,'Undersampled',14,ink,'bold',ha='center')
    arrow(803,542,803,571,grey)
    text(864,838,'Training bias',16,teal,'bold')
    text(1178,972,'Training fluctuations',16,teal,'bold')
    text(1277,595,'Quantum overfitting',16,orange,'bold')
    text(1346,float(yy(FLOOR))+32,'Test sampling',15,grey,'bold')
    text(947,638,r'$N^{-2}$',20,teal)
    text(1468,993,r'$N^{-1}$',20,teal)
    text(1410,665,r'$N$',20,orange)
    text(1190,1014,r'$N\sim n_{\mathrm{tr}}$',17,grey)
    text(1613,float(yy(noisy[-1])),r'$\gamma^2\,N/M$',20,orange)
    text(1613,float(yy(finite[-1])),r'$1/M$',20,grey)
    text(1613,float(yy(train[-1])),r'$M\rightarrow\infty$',19,dark_teal)
    # Inset: finite-shot bias floor as the training-set size increases.
    ix0,ix1,iy0,iy1=1530,1750,525,440
    arrow(ix0,iy0,ix1+5,iy0,grey)
    arrow(ix0,iy0,ix0,iy1-3,grey)
    u=np.linspace(0,1,150)
    ax.plot(ix0+13+u*(ix1-ix0-25),iy0-18-60*np.exp(-5*u),color=dark_teal,lw=1.9)
    ax.plot([ix0+8,ix1-7],[iy0-18,iy0-18],color=orange,lw=1,ls=(0,(5,4)))
    text(1657,419,r'Fixed $N$, exact targets',14,ink,ha='center')
    text(1518,443,'MSE',10,grey,ha='right')
    text(1755,528,r'$n_{\mathrm{tr}}$',12,grey)
    text(1710,487,'Bias floor',11,orange,ha='center')
    text(1529,548,r'$M\rightarrow\infty$',12,grey)
    return fig


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output-dir", type=Path, default=Path("."))
    parser.add_argument("--dpi", type=int, default=200)
    args = parser.parse_args()
    args.output_dir.mkdir(parents=True, exist_ok=True)
    fig = build_figure()
    for extension in ("pdf", "svg", "png"):
        target = args.output_dir / f"qlr_figure_matplotlib.{extension}"
        fig.savefig(target, dpi=args.dpi, facecolor="white")
        print(target)
    plt.close(fig)


if __name__ == "__main__":
    main()
