#!/usr/bin/env python3
"""Editable Matplotlib reconstruction of the quantum linear regression schematic.

Requirements: numpy, matplotlib and a LaTeX installation with the
amsfonts, amssymb, mathpazo and bm packages (no source images or PDF files needed).
Text is typeset with LaTeX in the same style as the other paper figures.
Run: python qlr_block_matplotlib.py --output-dir . --dpi 200

Exports PDF, SVG and PNG. All artists are generated by Matplotlib.
Panel a uses the fixed noiseless block decomposition (draft SM1.2, SM25, Eq. 27).
Blocks are schematic; colours encode asymptotic sizes, not signed matrix entries.
Assume n_tr > n_out > r and full row rank of the perturbed noise block.
The pseudoinverse bottom-right block shows its leading term, with O(1) omitted.
Panel c is illustrative,
not a fit or simulation. Edit A, B, FLOOR, AMP and CAP to change the curves.
Canvas coordinates are 1800 x 1160 (100 units per inch) with y pointing down:
panels b and c use y in [390, 1100] and panel a uses the strip above, up to y = -60.
"""
import argparse
from pathlib import Path
import numpy as np
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
from matplotlib.patches import Rectangle, FancyBboxPatch, Circle, Polygon


def build_figure():
    # Same LaTeX style as the other figures of the paper (Palatino via mathpazo).
    plt.rcParams["text.latex.preamble"] = r"\usepackage{amsfonts, amssymb, mathpazo,bm}"
    plt.rcParams.update({"text.usetex": True, "font.family": "serif",
                         "svg.fonttype": "none", "pdf.fonttype": 42})
    # Colour palette: one hue per mechanism, shared by all panels. The four line
    # colours pass colour-vision-deficiency (protan/deutan) and contrast checks as
    # a set; the darker "ink" steps of the same hues keep coloured text at >= 4.5:1,
    # also on the tinted regime bands of panel c.
    c_train,ink_train='#2a78d6','#1467c3'      # training-shot effects (blue)
    c_target,ink_target='#4a3aa7','#4a3aa7'    # classical target noise (violet)
    c_test,ink_test='#199e70','#00794e'        # test sampling, 1/M (green)
    c_over,ink_over='#eb6834','#be3e00'        # quantum overfitting (orange)
    ink='#282e34'; grey='#6b6a66'              # main text; neutral annotations
    dark_block='#d95926'                       # amplified-noise block in panel a (white text)
    band_alpha=0.16                            # opacity of the regime bands in panel c
    def tint(c,alpha):
     # Colour c at opacity alpha on the white page.
     return tuple(alpha*np.array(matplotlib.colors.to_rgb(c))+(1-alpha))
    top=-60                         # upper edge of the canvas; panel a lives in y < 390
    fig=plt.figure(figsize=(18,(1100-top)/100),facecolor='white')
    ax=fig.add_axes([0,0,1,1]);ax.set_xlim(0,1800);ax.set_ylim(1100,top);ax.axis('off')
    def text(x,y,s,size=14,color=ink,weight='normal',**kw):
     # With usetex the fontweight is ignored, so bold is applied in LaTeX,
     # line by line because Matplotlib typesets each line separately.
     if weight=='bold':
      s='\n'.join(r'\textbf{'+line+'}' for line in s.split('\n'))
     ax.text(x,y,s,fontsize=size,color=color,va='center',**kw)
    def arrow(x1,y1,x2,y2,color=grey):
     ax.annotate('',xy=(x2,y2),xytext=(x1,y1),arrowprops=dict(arrowstyle='->',lw=1.4,color=color))
    # Fixed noiseless subspaces: draft SM1.2, SM25, and Eq. (27).
    # P: supp(P) + ker(P) -> im(P) + coker(P).
    # Pseudoinversion reverses these domain/codomain decompositions.
    # Block colours encode asymptotic order, not individual signed entries.
    # Panel a layout, following the hand-made mock-up. Each column (title,
    # column labels, matrix, caption) is centred on its matrix. The matrices
    # rest on a common bottom edge and the captions share one row; the tall
    # pseudoinverse rises higher, so its title reaches the heading row.
    wide_w,wide_h=290,190           # feature matrices
    tall_w,tall_h=200,270           # pseudoinverse
    label_size,entry_size=20,19     # row/column labels and block entries
    title_size,caption_size=19,17
    col_x=[302,810,1267]            # column centres
    bottom=top+372                  # common bottom edge of the matrices
    caption_y=bottom+32
    wide_mid=bottom-wide_h/2        # the arrows sit at the centre of the wide matrices
    tall_mid=bottom-tall_h/2        # the outcome branch is centred on the pseudoinverse
    text(50,top+48,r'a\quad Shot noise lifts the rank',24,weight='bold')
    # Note on tau, on the heading row and left-aligned with the second matrix.
    text(col_x[1]-wide_w/2,top+48,r'Fixed noiseless subspaces; $\tau=N^{-1/2}$',17,grey)
    #text(col_x[2],top+43,r'white: zero\quad$\cdot$\quad pale: small\quad$\cdot$\quad dark: large',11,grey,ha='center')
    support=r'$\mathrm{supp}(P)$'
    kernel=r'$\ker(P)$'
    image=r'$\mathrm{im}(P)$'
    cokernel=r'$\mathrm{coker}(P)$'
    def blocks(cx,w,h,title,row_labels,col_labels,labels,colours):
        # 2x2 block matrix of size w x h, centred on cx and resting on `bottom`,
        # with its column labels and title stacked above it.
        x,y=cx-w/2,bottom-h
        text(cx,y-66,title,title_size,weight='bold',ha='center')
        for j,label in enumerate(col_labels):
            text(x+(j+.5)*w/2,y-25,label,label_size,ink,ha='center')
        for i,label in enumerate(row_labels):
            text(x-8,y+(i+.5)*h/2,label,label_size,ink,ha='right')
        for i in range(2):
            for j in range(2):
                ax.add_patch(Rectangle((x+j*w/2,y+i*h/2),w/2,h/2,
                    facecolor=colours[i][j],edgecolor='white',linewidth=2))
                text(x+(j+.5)*w/2,y+(i+.5)*h/2,labels[i][j],entry_size,
                     'white' if colours[i][j]==dark_block else ink,ha='center')
        ax.add_patch(Rectangle((x,y),w,h,fill=False,edgecolor='#aebac2',linewidth=.8))
        ax.plot([x+w/2,x+w/2],[y,y+h],color='#aebac2',lw=.7)
        ax.plot([x,x+w],[y+h/2,y+h/2],color='#aebac2',lw=.7)
    # Wide feature matrices; the pseudoinverse is correspondingly tall.
    blocks(col_x[0],wide_w,wide_h,'Ideal probabilities',[image,cokernel],[support,kernel],
           [[r'$P_{11}$',r'$0$'],[r'$0$',r'$0$']],
           [[tint(c_train,.4),'white'],['white','white']])
    blocks(col_x[1],wide_w,wide_h,'Finite-shot features',[image,cokernel],[support,kernel],
           [[r'$P_{11}+\tau\widehat\Xi_{11}$',r'$\tau\widehat\Xi_{12}$'],
            [r'$\tau\widehat\Xi_{21}$',r'$\tau\widehat\Xi_{22}$']],
           # Small noise blocks (order tau): a paler tint than the O(1) blocks of the pseudoinverse.
           [[tint(c_train,.4),tint(c_over,.18)],[tint(c_over,.18),tint(c_over,.18)]])
    blocks(col_x[2],tall_w,tall_h,'Pseudoinverse',[support,kernel],[image,cokernel],
           [[r'$O(1)$',r'$O(1)$'],[r'$O(1)$',r'$\sqrt{N}\,\widehat\Xi_{22}^{+}$']],
           [[tint(c_train,.4),tint(c_over,.4)],[tint(c_over,.4),dark_block]])
    # Each arrow sits midway between a matrix and the row labels of the next.
    row_label_w=117                 # widest row label plus its gap to the matrix
    def step(x_left,x_right,label):
        xm=(x_left+x_right)/2
        arrow(xm-36,wide_mid,xm+36,wide_mid)
        text(xm,wide_mid-22,label,15,grey,ha='center')
    step(col_x[0]+wide_w/2,col_x[1]-wide_w/2-row_label_w,'shots')
    step(col_x[1]+wide_w/2,col_x[2]-tall_w/2-row_label_w,'invert')
    text(col_x[0],caption_y,r'$\mathrm{rank}(P)=r\leq d^2$',caption_size,grey,ha='center')
    text(col_x[1],caption_y,'Noise populates the missing blocks',caption_size,ink_over,ha='center')
    text(col_x[2],caption_y,r'$\mathrm{coker}(P)\ \longrightarrow\ \ker(P)$',caption_size,ink_over,ha='center')
    # Outcome branch, centred on the pseudoinverse.
    upper,lower=tall_mid-55,tall_mid+55
    bx=col_x[2]+tall_w/2+40         # start of the branch, just right of the pseudoinverse
    ax.plot([bx,bx+45,bx+45],[tall_mid,tall_mid,upper],color='#d8e0e5',lw=1)
    ax.plot([bx+45,bx+45],[tall_mid,lower],color='#d8e0e5',lw=1)
    arrow(bx+45,upper,bx+80,upper,c_train)
    arrow(bx+45,lower,bx+80,lower,c_over)
    text(bx+92,upper,'Exact targets + exact test',16,ink_train,'bold')
    text(bx+92,upper+39,'Divergence cancels',16,ink_train)
    text(bx+92,lower,'Noisy targets + finite test',16,ink_over,'bold')
    text(bx+92,lower+39,'Quantum overfitting',16,ink_over)
    # Panel b: individual sources of prediction error.
    # Panel b and c titles share one row; panel c's title is aligned with its y axis.
    text(50,408,r'b\quad Origins of the MSE',24,weight='bold')
    text(777,408,r'c\quad Resources shape the MSE',24,weight='bold')
    def box(x,y,w,h,color,style='-'):
     ax.add_patch(FancyBboxPatch((x,y),w,h,boxstyle='round,pad=0,rounding_size=13',
                               facecolor='white',edgecolor=color,lw=1.1,linestyle=style))
    def group_label(y,lines,color):
     text(173,y,lines,14,color,'bold',ha='right',linespacing=1.3)
    def divider(y):
     ax.plot([205,658],[y,y],color='#d6dfe4',lw=1)
    box(188,451,485,170,c_train)
    group_label(520,'Training-shot\neffects',ink_train)
    divider(535)
    text(260,482,'Training bias',17,ink,'bold')
    text(260,513,'Training shot noise',14,ink_train)
    text(665,502,r'$N^{-2}$',26,ink_train,ha='right')
    text(260,561,'Training fluctuations',17,ink,'bold')
    text(260,595,'Training shot noise',14,ink_train)
    text(668,580,r'$1/(N\,n_{\mathrm{tr}})$',25,ink_train,ha='right')
    x=np.linspace(206,245,100)
    ax.plot(x,512-36*np.exp(-((x-227)/8)**2),color=c_train,lw=1.6)
    arrow(213,465,237,465,c_train)
    ax.scatter([215,234,220,241,212,232,224],[560,555,574,579,592,601,583],s=10,color=c_train)
    box(188,641,485,169,c_target)
    group_label(720,'Target noise\nClassical',ink_target)
    divider(726)
    text(260,672,'Training target noise',17,ink,'bold')
    text(260,705,'Noisy training labels',14,ink_target)
    text(665,685,r'$\gamma^2/n_{\mathrm{tr}}$',25,ink_target,ha='right')
    text(260,752,'Test target noise',17,ink,'bold')
    text(260,786,'Noisy test labels',14,ink_target)
    text(665,766,r'$\gamma^2$',26,ink_target,ha='right')
    ax.add_patch(Polygon([(210,665),(239,665),(250,685),(239,709),(210,709)],fill=False,edgecolor=c_target,lw=1.3))
    text(224,686,r'$\pm$',18,ink_target,ha='center')
    ax.add_patch(Circle((239,677),2.6,fill=False,edgecolor=c_target,lw=1))
    for radius in [12,22]:ax.add_patch(Circle((227,771),radius,fill=False,edgecolor=c_target,lw=1))
    ax.scatter([216,226,238],[769,762,783],s=13,color=c_target)
    box(188,831,485,84,c_test,'--')
    group_label(872,'Test-shot\neffect',ink_test)
    text(260,854,'Test sampling',17,ink,'bold')
    text(260,888,'Finite test shots',14,ink_test)
    text(665,878,r'$1/M$',26,ink_test,ha='right')
    for j,h in enumerate([16,33,25,42]):ax.add_patch(Rectangle((208+j*11,892-h),6,h,facecolor=c_test))
    box(188,936,485,112,c_over,'--')
    group_label(989,'Quantum\noverfitting',ink_over)
    text(260,961,'Quantum overfitting',17,ink,'bold')
    text(260,995,r'Training-shot noise ',13,ink_over)
    text(260,1022,r'$\times$ target noise$\times$ test-shot noise',13,ink_over)
    text(665,994,r'$\gamma^2\,N/M$',26,ink_over,ha='right')
    ax.plot([207,222,234],[1000,980,986],color=c_over,lw=1.7)
    arrow(234,986,251,963,c_over)
    # Panel c: schematic log-log resource curves, not experimental data.
    # The capped training contribution interpolates between an undersampled
    # plateau and A/N^2 + B/N. Test noise and label amplification are additive.
    N=np.logspace(-1,6,500)
    A,B,FLOOR,AMP,CAP=8e-3,2e-5,8e-7,8e-10,1e-2
    raw=A/N**2+B/N
    train=CAP*raw/(CAP+raw)
    finite=train+FLOOR
    noisy=finite+AMP*N
    X0,X1,Y0,Y1=777,1585,1034,566
    log_min,log_max=-12.0,-1.7
    xx=X0+(np.log10(N)+1)/7*(X1-X0)
    def yy(values):
     return Y0-(np.log10(values)-log_min)/(log_max-log_min)*(Y0-Y1)
    # Regime map, as in the first version of this panel: two vertical bands
    # (undersampled plateau, training bias) and, beyond N ~ n_tr, three
    # rectangles (quantum overfitting above the 1/M level, test sampling
    # around it, training fluctuations below it). Edges follow the model.
    def xN(n):
     return X0+(np.log10(n)+1)/7*(X1-X0)
    x_under=xN(np.sqrt(A/CAP)/3)    # training error 10% below its plateau
    x_cross=xN(A/B)                 # bias = fluctuations, i.e. N ~ n_tr
    x_over=xN(FLOOR/AMP)            # label amplification = test sampling
    y_over,y_fluct=yy(2*FLOOR),yy(FLOOR/40)   # edges of the test-sampling strip
    def region(x0,x1,y_top,y_bottom,color):
     ax.add_patch(Rectangle((x0,y_top),x1-x0,y_bottom-y_top,facecolor=color,edgecolor='none'))
    region(X0,x_under,Y1,Y0,tint(grey,band_alpha))        # undersampled
    region(x_under,x_cross,Y1,Y0,tint(c_train,band_alpha))   # training bias
    region(x_cross,X1,Y1,y_fluct,tint(c_test,band_alpha))   # test sampling
    region(x_over,X1,Y1,y_over,tint(c_over,band_alpha))     # quantum overfitting
    region(x_cross,X1,y_fluct,Y0,tint(c_train,band_alpha))   # training fluctuations
    # Crossover N ~ n_tr: dashed grey vertical line across the plot, under the curves.
    ax.plot([x_cross,x_cross],[Y0,Y1],color=grey,lw=1.6,ls=(0,(5,4)))
    arrow(X0,Y0,X1+19,Y0,ink)
    arrow(X0,Y0,X0,Y1-15,ink)
    text(733,798,'MSE',19,ink,rotation=90,ha='center')
    text(1190,1076,r'Training shots per state, $N$',20,ink,ha='center')
    # Reproducible pseudo-experimental traces convey fluctuations without representing data.
    rng=np.random.default_rng(7)
    for curve,color,smooth in [(train,c_train,ink_train),(finite,c_test,ink_test),(noisy,c_over,ink_over)]:
     for _ in range(2):
      perturb=np.exp(rng.normal(0,.22,len(N[::5])))
      ax.plot(xx[::5],yy(curve[::5]*perturb),color=color,alpha=.7,lw=1.8)
     ax.plot(xx,yy(curve),color=smooth,lw=2.7,solid_capstyle='round')
    # Asymptotic fits: thick black dashed lines, offset parallel to their curves
    # (in log scale, by the factor `shift`) so that neither the smooth curves
    # nor the pseudo-experimental traces cover them.
    shift=10**0.6
    fits=[(lambda n:A/n**2*shift,(N>2)&(N<40)),    # above the training-bias curve
          (lambda n:B/n/shift,N>1e3),               # below the training-fluctuation curve
          (lambda n:AMP*n*shift,N>1e4),             # above the quantum-overfitting curve
          (lambda n:FLOOR/shift*np.ones_like(n),N>1e3)]   # below the 1/M test-sampling plateau
    for f,mask in fits:
     ax.plot(xx[mask],yy(f(N[mask])),color='black',lw=3.2,ls=(0,(4,3)))
    def fit_label(f,n0,label,color,side,dist=48):
     # Label a fit at N=n0, offset by `dist` along the normal to the line so it
     # never touches it: side=+1 puts the label above the line, side=-1 below.
     xa,xb=X0+(np.log10([n0,n0*1.1])+1)/7*(X1-X0)
     ya,yb=yy(f(n0)),yy(f(n0*1.1))
     L=np.hypot(xb-xa,yb-ya); nx,ny=(yb-ya)/L,-(xb-xa)/L
     text(xa+side*dist*nx,ya+side*dist*ny,label,24,color,ha='center')
    # 'Undersampled' label and arrow, centred on the undersampled band.
    text((X0+x_under)/2,522,'Undersampled',20,ink,'bold',ha='center')
    arrow((X0+x_under)/2,545,(X0+x_under)/2,574,grey)
    text((x_under+x_cross)/2,838,'Training bias',20,ink_train,'bold',ha='center')
    text(x_cross+14,1000,'Training fluctuations',20,ink_train,'bold')   # just right of the crossover line
    text((x_over+X1)/2,589,'Quantum overfitting',20,ink_over,'bold',ha='center')
    text(1346,float(yy(FLOOR/shift))+25,'Test sampling',19,ink_test,'bold')   # just below the 1/M fit
    # Fit labels at the middle of each fit, clear of the dashed lines.
    # Fit labels on the side of each fit away from its curve.
    fit_label(fits[0][0],10,r'$N^{-2}$',ink_train,+1)
    fit_label(fits[1][0],3e3,r'$N^{-1}$',ink_train,-1)
    fit_label(fits[2][0],2e4,r'$N$',ink_over,+1)
    text(x_cross-14,1010,r'$N\approx n_{\mathrm{tr}}$',20,grey,ha='right')   # just left of the crossover line
    text(1613,float(yy(noisy[-1])),r'$\gamma^2\,N/M$',20,ink_over)
    text(1613,float(yy(finite[-1])),r'$1/M$',20,ink_test)
    text(1613,float(yy(train[-1])),r'$M\rightarrow\infty$',19,ink_train)
    # Inset: finite-shot bias floor as the training-set size increases.
    ix0,ix1,iy0,iy1=1530,1750,525,440
    arrow(ix0,iy0,ix1+5,iy0,grey)
    arrow(ix0,iy0,ix0,iy1-3,grey)
    u=np.linspace(0,1,150)
    ax.plot(ix0+13+u*(ix1-ix0-25),iy0-18-60*np.exp(-5*u),color=ink_train,lw=1.9)
    ax.plot([ix0+8,ix1-7],[iy0-18,iy0-18],color=c_over,lw=1,ls=(0,(5,4)))
    text(1657,419,r'Fixed $N$, exact targets',14,ink,ha='center')
    text(1518,443,'MSE',10,grey,ha='right')
    text(1755,528,r'$n_{\mathrm{tr}}$',12,grey)
    text(1710,487,'Bias floor',11,ink_over,ha='center')
    text(1529,548,r'$M\rightarrow\infty$',12,grey)
    return fig


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output-dir", type=Path, default=Path("."))
    parser.add_argument("--dpi", type=int, default=200)
    args = parser.parse_args()
    args.output_dir.mkdir(parents=True, exist_ok=True)
    fig = build_figure()
    for extension in ("pdf", "svg", "png"):
        target = args.output_dir / f"qlr_block_matplotlib.{extension}"
        fig.savefig(target, dpi=args.dpi, facecolor="white")
        print(target)
    plt.close(fig)


if __name__ == "__main__":
    main()
